name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.21', '1.20']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install Z3 (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libz3-dev pkg-config
      - name: Install Z3 (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install z3 pkg-config
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -v
